function [mod] = SVM_Model(Data, Label, mod, polOrder)



classificationSVM = fitcsvm(...
        Data, ...
        Label, ...
        'KernelFunction', mod, ...
        'PolynomialOrder', polOrder, ...
        'KernelScale', 'auto', ...
        'BoxConstraint', 1, ...
        'Standardize', true, ...
        'ClassNames', [0; 1]);
        
mod = classificationSVM;
 

end

